Locations:
  Spawn: #This is where the waiting room is to join the game
    x: 0
    y: 0
    z: 0
  Lobby: #This is where the main lobby is
   x: 0
   y: 0
   z: 0
  Bases: #This is where the players are teleported when the game start
   BlueBase:
     x: 0
     y: 0
     z: 0
   RedBase:
     x: 0
     y: 0
     z: 0
   GreenBase:
     x: 0
     y: 0
     z: 0
   YellowBase:
     x: 0
     y: 0
     z: 0
Walls:
  wall1: #Set the cords of the first wall like the fill command
    cord1:
      x: 0
      y: 0
      z: 0
    cord2:
      x: 0
      y: 0
      z: 0
  wall2: ##Set the cords of the second wall like the fill command
    cord1:
      x: 0
      y: 0
      z: 0
    cord2:
      x: 0
      y: 0
      z: 0
MinPlayers: 2 #Minimum players needed to start the game
map: miniwalls #the name of the map in the scoreboard
server: play.miniwalls.net #your server name
reset: 0 #don't touch this, if you do you will break the map reload system